services:
  app:
    image: python:3.11
    container_name: verily
    working_dir: /app
    restart: unless-stopped
    volumes:
      - .:/app
    command: sh -c "pip install -r requirements.txt && python main.py"
    ports:
      - "8080:8080"
      - "25:25"